version: '3.8'

services:
  gazebo:
    image: ros_noetic_gazebo_demo
    build: 
      context: "."
      platforms:
        - "linux/amd64"

    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      - XDG_RUNTIME_DIR=/tmp/runtime-root
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ./ros_ws:/root/ros_ws:rw
    devices:
      - /dev/dri:/dev/dri
    tty: true
    command: /bin/bash